spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/branchsync
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  security:
    user:
      name: user
      password: jddksddksdh

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8082
  servlet:
    context-path: /branchsync

auth:
  token: lkdkldlkalfnaddeereefeat.ereraercatervrrcssrcsrcsr.rsvrscsrcsrscrcsysrvy

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
