spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/branchsync
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  security:
    user:
      name: user
      password: jddksddksdh

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

server:
  port: 8082
  servlet:
    context-path: /branchsync

auth:
  token: lkdkldlkalfnaddeereefeat.ereraercatervrrcssrcsrcsr.rsvrscsrcsrscrcsysrvy